const Portfolio_data = [
    {
      id: 1,
      category: "MACHINE LEARNING PROJECT",
      totalLike: "600",
      title: "The services provide for Machine learning projects using Django",
      image: "https://i.ibb.co/5rQB2b9/image.png",
      link1: "https://i.ibb.co/5njcHKs/image.png",
      desc1: "Manual analysis of ECG signals is laborious and prone-to-error task, even for specialist with many hours of experience. For this reason develop software which is fully functional expert system for automatic diagnosis of different diseases i.e system a useful support tool for diagnosis",
      link2: "https://github.com/sandip-kumar-roy/a-ECG-diagnostic-System-software",
    },
    {
      id: 2,
      category: "REACT JS PROJECTS",
      totalLike: "750",
      title: "The services provide for React js project using React",
      image: "https://i.ibb.co/CvKwFL3/image.png",
      link1: "https://i.ibb.co/dKrDtvD/image.png",
      desc1: "News App using React From where We can view all the current as well as old news with a search bar provided so that we can serach any new from there",
      link2: "https://github.com/sandip-kumar-roy",
    },
    {
      id: 3,
      category: "DOT NET PROJECTS",
      totalLike: "630",
      title: "The services provide for  Dot net projects using ASP.Net ",
      image: "https://i.ibb.co/0QcDKcp/image.png",
      link1: "https://i.ibb.co/q5V6WT2/image.png",
      desc1: "SuperMarket Inventory ,Customers, Pricing, Billing, Orders ,will be there which makes it easier for a shop owner to keep track of all details inside a database using Dot net ( c# )",
      link2: "https://github.com/sandip-kumar-roy",
    },
    {
      id: 4,
      category: "SYSTEM DESIGN ",
      totalLike: "360",
      title: "The services provide for system design",
      image: "https://i.ibb.co/bBBnftX/image.png",
      link1: "https://i.ibb.co/MnC3cDQ/image.png",
      desc1: "It is basically an ADMIN DASHBOARD which provide details about all different users available on the platform using a coool ui/ux design with graphs and symbols",
      link2: "https://github.com/sandip-kumar-roy",
    },
    {
      id: 5,
      category: "JAVA PROJECTS",
      totalLike: "280",
      title: "The services provide for java projects projects using J2EE",
      image: "https://i.ibb.co/wSKPbQZ/image.png",
      link1: "https://i.ibb.co/sVtnhWn/image.png",
      desc1: "It is suitable for both JOB SEEKER and JOB POSTER(RECRUITER) where one can either search for job related posting and one can put new job openings .A search option is also provided which enhance the user interaction instead of scrolling down they can type their required jobs too search",
      link2: "https://github.com/sandip-kumar-roy/Enterprise-Inventory-system",
    },
    {
      id: 6,
      category: "CLOUD COMPUTING RELATED PROJECTS",
      totalLike: "690",
      title: "App for tecnology & services",
      image: "https://i.ibb.co/pv3bHsL/image.png",
      link1: "https://i.ibb.co/287w0Lv/image.png",
      desc1: "smart Traffic management system will be there which makes our work in an automated mode",
      link2: "https://github.com/sandip-kumar-roy",
    },
  ]
  export default Portfolio_data
